=== ibab/lhcb-software/LHCb/Event/TrackEvent/xml/gdd.dtd
<?xml encoding="UTF-8"?>
<!-- ?xml encoding="ISO-8859-1"? -->
<!ELEMENT gdd ((import*, package+)+)>
<!ATTLIST gdd
        version          CDATA                             "1.0"
>
<!ELEMENT import EMPTY>
<!ATTLIST import
        name             CDATA                             #REQUIRED
        std              (TRUE | FALSE)                    "FALSE"
        soft             (TRUE | FALSE)                    "FALSE"
        ignore           (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT package ((import*, class*, namespace*, assoc*)*)>
<!ATTLIST package
        name             CDATA                             #REQUIRED
>
<!-- ELEMENT class ((class?, ..... -->
<!ELEMENT class ((desc?, base?, import?, location?, enum?, typedef?, constructor?, destructor?, method?, attribute?, relation?, template?)*)>
<!-- candidates 4 deprication: filename, templateVector, templateList, serializers -->
<!ATTLIST class
        name              CDATA                            #REQUIRED
        author            CDATA                            #REQUIRED
        desc              CDATA                            #REQUIRED
        filename          CDATA                            #IMPLIED  
        id                CDATA                            #IMPLIED
        version           CDATA                            #IMPLIED
        location          CDATA                            #IMPLIED
        stdVectorTypeDef  (TRUE | FALSE)                   "FALSE"  
        keyedContTypeDef  (TRUE | FALSE)                   "FALSE"  
	contObjectTypeDef (TRUE | FALSE)                   "FALSE"
        templateVector    (TRUE | FALSE)                   "TRUE"    
        templateList      (TRUE | FALSE)                   "TRUE"    
        serializers       (TRUE | FALSE)                   "TRUE"    
>       
<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc
        xml:space        (default | preserve)              #FIXED "preserve"
>
<!ELEMENT location EMPTY>
<!ATTLIST location
        name             CDATA                             #REQUIRED
        place            CDATA                             #REQUIRED
        noQuote          (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT namespace ((desc?, typedef?, enum?, class?, import?, attribute?, method?)*)>
<!ATTLIST namespace
        name             CDATA                             #REQUIRED
        author           CDATA                             #IMPLIED
        desc             CDATA                             #REQUIRED
>
<!ELEMENT base EMPTY>
<!ATTLIST base
        name             CDATA                             #REQUIRED
        virtual          (TRUE | FALSE)                    "FALSE"
        access           (PUBLIC | PROTECTED | PRIVATE)    "PUBLIC"
>
<!ELEMENT enum EMPTY>
<!ATTLIST enum
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        value            CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
>
<!ELEMENT typedef EMPTY>
<!ATTLIST typedef 
        desc             CDATA                             #REQUIRED
        type             CDATA                             #REQUIRED
        def              CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
>
<!ELEMENT constructor (arg*, code?, arg*)>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST constructor
        desc             CDATA                             #REQUIRED
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED   
        initList         CDATA                             #IMPLIED
        explicit         (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT destructor (arg*, code?, arg*)>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST destructor
        desc             CDATA                             #REQUIRED
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED  
>
<!ELEMENT method ((arg*, return?, arg*, code?, arg*) | (arg*, code?, arg*, return?, arg*))>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST method
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        template         CDATA                             #IMPLIED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PUBLIC"
        const            (TRUE | FALSE)                    "FALSE"
        virtual          (TRUE | FALSE | PURE)             "FALSE"
        static           (TRUE | FALSE)                    "FALSE"
        inline           (TRUE | FALSE)                    "FALSE"
        friend           (TRUE | FALSE)                    "FALSE"
        type             CDATA                             "void"
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED  
>
<!ELEMENT arg EMPTY>
<!ATTLIST arg
        type             CDATA                             #REQUIRED
        name             CDATA                             #IMPLIED
        const            (TRUE | FALSE)                    "FALSE"
        inout            (BYVALUE | INPUT | INOUT | BOTH)  "INPUT"
>
<!ELEMENT return EMPTY>
<!ATTLIST return
        type             CDATA                             #REQUIRED
        const            (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
        xml:space        (default | preserve)              #FIXED "preserve"
>
<!ELEMENT attribute (bitfield*)>
<!-- candidates 4 deprication: array, serialize -->
<!ATTLIST attribute
        type             CDATA                             #REQUIRED
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        init             CDATA                             #IMPLIED
        dictalias        CDATA                             #IMPLIED
        array            CDATA                             "FALSE"    
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
        compression      (TRUE | FALSE)                    "TRUE"
        serialize        (TRUE | FALSE)                    "TRUE"     
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        transient        (TRUE | FALSE)                    "FALSE"    
>
<!ELEMENT relation EMPTY>
<!ATTLIST relation
        type             CDATA                             #REQUIRED
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
        multiplicity     (1 | N | n | M | m)               "1"
        serialize        (TRUE | FALSE)                    "TRUE"
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        addMeth          (TRUE | FALSE)                    "TRUE"
        remMeth          (TRUE | FALSE)                    "TRUE"
        clrMeth          (TRUE | FALSE)                    "TRUE"
>
<!ELEMENT bitfield EMPTY>
<!ATTLIST bitfield
        name             CDATA                             #REQUIRED
        type             CDATA                             #IMPLIED
        length           CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        startBit         CDATA                             #IMPLIED
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        checkMeth        (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT template EMPTY>
<!ATTLIST template
        name             CDATA                             #REQUIRED
        t1               CDATA                             "THIS"
        t2               CDATA                             #IMPLIED
        t3               CDATA                             #IMPLIED
        t4               CDATA                             #IMPLIED
>

<!ELEMENT assoc EMPTY>
<!ATTLIST assoc
        type             (1D | 2D)                         "1D"
        weight           CDATA                             "NONE"
        from             CDATA                             #REQUIRED
        to               CDATA                             #REQUIRED
>

<!ENTITY KeyedObjectKey 'int'>
<!ENTITY Reference '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>'
>
<!ENTITY StlVector '<template name="VectorDict" t1="THIS"/>'
>
<!ENTITY StlPtrVector '<template name="VectorDict" t1="THIS*"/>'
>
<!ENTITY DataObject '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>'
>
<!ENTITY ContainedObject '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>'
>
<!ENTITY KeyedContainer '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>
        <template name="KeyedContainerDict"/>'
>
<!ENTITY KeyedObject '<template name="KeyedObjectDict" t1="int"/>
        <template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>
        <template name="KeyedContainerDict"/>'
>

=== ibab/lhcb-software/LHCb/Event/GenEvent/xml/GenHeader.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd" >
<gdd>
  <package name='GenEvent'>
<!-- ****************************************************************
     * GenHeader                                                    *
     ****************************************************************-->
     <class 
      author="Marco Cattaneo, revised by P. Koppenburg, then G.Corti"
      desc="Header for event generator information"
      name="GenHeader"
      location="Gen/Header"
      id="102"
     >
       &DataObject;
       <base name="ProcessHeader"/>
       <import name="Event/ProcessHeader"/>
      <import name="BeamParameters" soft="TRUE"/>
       <import name="GenCollision" soft="TRUE"/>
      <constructor
       desc="Constructor"
       initList = "m_luminosity(0.0), m_evType(0), m_evtNumber(0), m_totCrossSection(0.0), m_crossingFreq(0.0)" >
	<code>
	  setVersion( '2' );
	</code>
      </constructor>
       <attribute 
	desc="Retrieve const Instantaneous luminosity used for pileUp probability (for backward compatibility)"
        name="luminosity"
        type="double"
        init="0.0"
        setMeth="FALSE"
        getMeth="FALSE"
       />
       <attribute
        desc='LHCb event type. Code used in BookKeeping to identify samples, as defined in &lt;a href="http://cdsweb.cern.ch/record-restricted/855452/"&gt;LHCb-2005-034&lt;/a&gt;'
        name="evType"
        type="int"
        init="0"
       />
       <attribute
        desc="Event number"
        name="evtNumber"
        type="long long"
        init="0"
       />
       <attribute 
	desc="Retrieve const Total cross section used for pileUp probability (for backward compatibility)"
        name="totCrossSection"
        type="double"
        init="0.0"
        setMeth="FALSE"
        getMeth="FALSE"
       />
       <attribute 
	desc="Retrieve const Filled-filled bunches crossing frequency (for backward compatibility)"
        name="crossingFreq"
        type="double"
        init="0.0"
        setMeth="FALSE"
        getMeth="FALSE"
       />
       <relation
        desc="Pointer to collisions in this event"
        multiplicity="N"
        name="collisions"
        type="LHCb::GenCollision"
       />
      <relation
        desc="Pointer to beam parameters in this event"
        multiplicity="1"
        name="beamParameters"
        type="LHCb::BeamParameters"
        />
       <method
        const="TRUE"
        desc="Number of collisions in bunch crossing"
        name="numOfCollisions"
        type="unsigned int"
       >
	<code>
	  return collisions().size();
        </code>
       </method>
      <method
	const="TRUE"
	desc="Retrieve instantaneous luminosity used for pileup probability"
        name="luminosity"
        type="double"
      >
	<code>
         return ( '2' != version() ? m_luminosity : 
	  beamParameters() ? beamParameters()->luminosity() 
          : m_luminosity );
        </code>
      </method>
      <method
        const="TRUE"
        desc="Retrieve total cross-section used for pileup probability"
        name="totCrossSection"
        type="double"
      >
        <code>
         return ( '2' != version() ? m_totCrossSection : 
          beamParameters() ? beamParameters()->totalXSec() 
          : m_totCrossSection );
        </code>
      </method>
      <method
        const="TRUE"
        desc="Retrieve filled-filled bunches crossing frequency"
        name="crossingFreq"
        type="double"
      >
        <code>
         return ( '2' != version() ? m_crossingFreq : 
	  beamParameters() ? beamParameters()->revolutionFrequency() 
          : m_crossingFreq );
        </code>
      </method>
     </class>
  </package>
</gdd>

=== ibab/lhcb-software/Rec/Tr/TrackFitEvent/xml/STLiteMeasurement.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'[
<!ENTITY OUTTYPE "STLiteMeasurement">
<!ENTITY INTYPE "STLiteCluster">
<!ENTITY ACCESSOR ".">
<!ENTITY POINTER "">
<!ENTITY STCommon SYSTEM "STMeasurement.ent">
]
>
<gdd>
  <package name='TrackFitEvent'>

<!-- ================ STLiteMeasurement class definition ================ -->

    <class
      name        = 'STLiteMeasurement'
      author      = 'M Needham'
      desc        = 'STLiteMeasurement is a measurement made from a STLite cluster (of TT, IT or UT).'
      defaultconstructor ='FALSE'
      serializers = 'FALSE'>

      <base name='LHCb::Measurement' />
      <import name='Event/Measurement' />
      <import name='Event/STLiteCluster' />
      <import name='StateVector' soft='FORWARDONLY'/>
      <import name='STDet/DeSTDetector.h' />
      <import name='STDet/DeSTSector' />
      <import name='TrackInterfaces/ISTClusterPosition' />

 
      <attribute
        type = 'LHCb::STLiteCluster'
        name = 'cluster'
        desc = 'Access to the STLiteCluster'
        getMeth = 'TRUE'
        setMeth = "FALSE" />


        &STCommon;

<method
  type    = 'unsigned int'
  name    = 'size'
  desc    = 'cluster size'
  const   = 'TRUE'>
  <code>
     return m_cluster.pseudoSize();
  </code>
</method>


    </class>

  </package>
</gdd>

=== ibab/lhcb-software/LHCb/Event/DigiEvent/xml/VeloPixDigit.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM "gdd.dtd" >
<gdd>
 <package name="DigiEvent">
  <class
   author="Marcin Kucharczyk"
   desc="This class represents digitized pixel hit in VeloPix"
   id="4503"
   name="VeloPixDigit">
   <location name="VeloPixDigitLocation"   place="Raw/VP/Digits"   />
   <import name="Kernel/VeloPixChannelID"/>
   <template name="KeyedObjectDict" t1="LHCb::VeloPixChannelID"/>
   <base name="KeyedObject&lt;LHCb::VeloPixChannelID&gt;"/>
   &KeyedContainer;

   <constructor argList="int tot"
                initList="m_ToTValue(tot),m_timeStamp(0)"
                desc="constructor from ToT charge only">
   </constructor>

   <constructor argList="int tot, int time"
                initList="m_ToTValue(tot),m_timeStamp(time)"
                desc="constructor from ToT and time stamp">
   </constructor>

  <constructor desc = 'copy constructor'
      initList = "KeyedObject&lt;LHCb::VeloPixChannelID&gt;(),m_ToTValue(digit.m_ToTValue),m_timeStamp(digit.m_timeStamp)" >
      <arg const = 'TRUE' name = "digit" type = "LHCb::VeloPixDigit" />
  </constructor>

  <method desc= 'clone method'
   name = 'clone'
   const = 'TRUE'
   type = "LHCb::VeloPixDigit*"
   access = "PUBLIC">
   <code>
     return new LHCb::VeloPixDigit( *this );
   </code>
  </method>

  <attribute name="ToTValue" type="int" desc="total digitized charge in a pixel measured as Time-over-Threshold "/>
  <attribute name="timeStamp" type="int" desc="time stamp related to when the threshold was exceeded"/>
  <method type='LHCb::VeloPixChannelID' name='channelID' const='TRUE' desc='channel = key'>
   <code>return key();</code>
  </method>

  </class>
 </package>
</gdd>

=== ibab/lhcb-software/LHCb/Event/RecEvent/xml/RecHeader.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd" >
<gdd>
  <package name='RecEvent'>
<!-- ****************************************************************
     * RecHeader                                                    *
     ****************************************************************-->
     <class 
      author="M. Cattaneo"
      desc="Header for reconstruction information"
      name="RecHeader"
      id="105"
     >
       <import name="string"  std="TRUE"/>
       
       <location name= "Default"
                 place="LHCb::ProcessHeaderLocation::Rec"
                 noQuote="TRUE"
       />

       &DataObject;
       <base name="ProcessHeader"/>
       <import name="Event/ProcessHeader"/>
       <attribute
        desc="Event number (same as in ODIN)"
        name="evtNumber"
        type="long long"
        init="0"
       />
       <attribute
        name="gpsTime"
        desc="GPS Time (same as in ODIN, microseconds)"
        type="unsigned long long"
        init="0"
       />
       <attribute
        name="rawID"
        desc="UUID of the raw file to which this event belongs"
        type="std::string"
       />

       <constructor 
		desc     = "Copy constructor. Creates a new RecHeader with the same information." 
		initList = "ProcessHeader(head), m_evtNumber(head.evtNumber()), m_gpsTime(head.gpsTime()), m_rawID(head.rawID())">
                <arg const="TRUE" name="head" type="LHCb::RecHeader"/>
                <code/>
       </constructor>
     </class>
  </package>
</gdd>

=== ibab/lhcb-software/LHCb/Kernel/LHCbKernel/xml/HitPattern.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>
  <package name="LHCbKernel">

    <class
       name   = "HitPattern"
       desc   = "pattern of hits used on tracks"
       author = "Stephanie Hansmann-Menzemer and Wouter Hulsbergen (2009)"
       virtual= "FALSE" >
          
       <import name="Kernel/LHCbID"/> 
       <import name = "bitset"  std = "TRUE" />
       <import name = "vector"  std = "TRUE" />       
       
       <enum
          desc   = "number of detector layers/regions"
          name   = "Number"
          value  = "NumVelo=24,NumTT=4,NumT=12, NumMuon=5"
          access = 'PUBLIC'
       />
 
       <typedef
	   def    = "VeloPattern"
	   type   = "std::bitset&lt;24&gt;"
	   desc   = "Velo hit pattern"
	   access = "PUBLIC" />

       <typedef
	   def    = "TTPattern"
	   type   = "std::bitset&lt;4&gt;"
	   desc   = "TT hit pattern"
	   access = "PUBLIC" />

       <typedef
	   def    = "TPattern"
	   type   = "std::bitset&lt;12&gt;"
	   desc   = "T-station hit pattern"
	   access = "PUBLIC" />

       <typedef
	   def    = "MuonPattern"
	   type   = "std::bitset&lt;5&gt;"
	   desc   = "Muon station hit pattern"
	   access = "PUBLIC" />

       <constructor
          desc     = 'Constructor from LHCbIDs'
          argList  = 'std::vector&lt;LHCbID&gt; ids'          >
       </constructor>


       <constructor
          desc = "Default Constructor">
       </constructor>

       <method 
          name    = "fillStream" 
          desc    = "Print this HitPattern"
          type    = "std::ostream&amp;" 
          virtual = "FALSE" 
          const   = "TRUE">
          <arg 
            type = "std::ostream" 
            name = "s"/>
      </method>


        <method
         type    = 'TPattern'
         name    = 'it'
         const   = 'TRUE'
        desc    = 'it layer pattern'>
         <code>
            return (m_itAC | m_itTopBottom);
         </code>
       </method>
 
       <method
         type    = 'TPattern'
         name    = 'ot'
         const   = 'TRUE'
         desc    = 'ot layer pattern'>
         <code>
            return (m_ot1stMonoLayer | m_ot2ndMonoLayer);
         </code>
       </method> 

     <method
         type    = 'VeloPattern'
         name    = 'velo'
         const   = 'TRUE'
         desc    = 'velo layer pattern'>
         <code>
            return (m_veloRA | m_veloRC | m_veloPhiA | m_veloPhiC );
         </code>
       </method> 



      <method
         type    = 'size_t'
         name    = 'numVeloR'
         const   = 'TRUE'
         desc    = 'number of velo R hits'>
         <code>
            return (m_veloRA.count() + m_veloRC.count());
         </code>
       </method> 

       <method
         type    = 'size_t'
         name    = 'numVeloPhi'
         const   = 'TRUE'
         desc    = 'number of velo phi hits'>
         <code>
            return (m_veloPhiA.count() + m_veloPhiC.count());
         </code>
       </method>

        <method
         type    = 'size_t'
         name    = 'numOTHits'
         const   = 'TRUE'
         desc    = 'number of OT hits, both monolayers'>
         <code>
            return (m_ot1stMonoLayer.count() + m_ot2ndMonoLayer.count());
         </code>
       </method> 

       <method
         type    = 'size_t'
         name    = 'numITHits'
         const   = 'TRUE'
         desc    = 'number of IT hits'>
         <code>
            return (m_itAC.count() + m_itTopBottom.count());
         </code>
       </method>

        <method
         type    = 'size_t'
         name    = 'numTTHits'
         const   = 'TRUE'
         desc    = 'number of TT hits'>
         <code>
            return (m_tt.count());
         </code>
       </method>

       <method
         type    = 'size_t'
         name    = 'numUTHits'
         const   = 'TRUE'
         desc    = 'number of UT hits'>
         <code>
            return (m_tt.count());
         </code>
       </method>

       <method
         type    = 'size_t'
         name    = 'numVeloStations'
         const   = 'TRUE'
         desc    = 'number of velo stations with one R or phi hit'>
         <code>
            return (velo().count());
         </code>
       </method>
        
       <method
         type    = 'size_t'
         name    = 'numVeloStationsOverlap'
         const   = 'TRUE'
         desc    = 'number of velo stations with one R or phi hit on both A and C side'>
       </method>

       
       <method
         type    = 'size_t'
         name    = 'numITStationsOverlap'
         const   = 'TRUE'
         desc    = 'number of it stations with hit in more than one box'>
       </method>

       <method
         type    = 'size_t'
         name    = 'numITOTStationsOverlap'
         const   = 'TRUE'
         desc    = 'number of T stations with hits in both IT and OT'>
       </method>

        <method
         type    = 'size_t'
         name    = 'numVeloHoles'
         const   = 'TRUE'
         desc    = 'number of holes in velo (layer) pattern'>
       </method>

        <method
         type    = 'size_t'
         name    = 'numTLayers'
         const   = 'TRUE'
         desc    = 'number of T layers'>
         <code>
            return ((ot() | it()).count());
         </code>
       </method>

        <method
         type    = 'size_t'
         name    = 'numTHoles'
         const   = 'TRUE'
         desc    = 'number of holes in T (layer) pattern'>
       </method>


        <method
         type    = 'void'
         name    = 'reset'
         const   = 'FALSE'
         desc    = 'reset bit maps'>
         <code>
           m_veloRA.reset();  
           m_veloRC.reset(); 
           m_veloPhiA.reset();  
           m_veloPhiC.reset();
	
	   m_tt.reset();
		  
	   m_itAC.reset();
           m_itTopBottom.reset();

	   m_ot1stMonoLayer.reset();
           m_ot2ndMonoLayer.reset();	   
	
	   m_muon.reset();
   
         </code>
       </method>

      <method
         type    = 'bool'
         name    = 'operator=='
         argList = 'const HitPattern hitPat'
         const   = 'TRUE'
         desc    = 'comparison equality'>
       </method>

     <attribute
        type      = 'VeloPattern'
        name      = 'veloRA'
        desc      = 'Velo R hit pattern on detector A side'
        access    = 'PRIVATE'
        setMeth   = 'TRUE'
        getMeth   = 'TRUE' />   

     <attribute
        type      = 'VeloPattern'
        name      = 'veloRC'
        desc      = 'Velo R hit pattern on detector C side'
        access    = 'PRIVATE'
        setMeth   = 'TRUE' 
        getMeth   = 'TRUE' />   


     <attribute
        type      = 'VeloPattern'
        name      = 'veloPhiA'
        desc      = 'Velo Phi hit pattern on detector A side'
        access    = 'PRIVATE'
        setMeth   = 'TRUE'
        getMeth   = 'TRUE' />   

     <attribute
        type      = 'VeloPattern'
        name      = 'veloPhiC'
        desc      = 'Velo Phi hit pattern on detector C side'
        access    = 'PRIVATE'
        setMeth   = 'TRUE' 
        getMeth   = 'TRUE' />     

     <attribute
        type      = 'TPattern'
        name      = 'ot1stMonoLayer'
        desc      = 'ot hit pattern in 1st monolayer'
        access    = 'PRIVATE'
        setMeth   = 'TRUE'
        getMeth   = 'TRUE' />   

    <attribute
        type      = 'TPattern'
        name      = 'ot2ndMonoLayer'
        desc      = 'ot hit pattern in 2nd monolayer'
        access    = 'PRIVATE'
        setMeth   = 'TRUE'
        getMeth   = 'TRUE' />   

     <attribute
        type      = 'TPattern'
        name      = 'itAC'
        desc      = 'it bit pattern in A and C side boxes'
        access    = 'PRIVATE'
        setMeth   = 'TRUE' 
        getMeth   = 'TRUE' />   

    <attribute
        type      = 'TPattern'
        name      = 'itTopBottom'
        desc      = 'it bit pattern in top and bottom boxes'
        access    = 'PRIVATE'
        setMeth   = 'TRUE' 
        getMeth   = 'TRUE' /> 

     <attribute
        type      = 'TTPattern'
        name      = 'tt'
        desc      = 'tt bit pattern'
        access    = 'PRIVATE'
        setMeth   = 'TRUE'
        getMeth   = 'TRUE' />  

     <attribute
        type      = 'MuonPattern'
        name      = 'muon'
        desc      = 'muon bit pattern'
        access    = 'PRIVATE'
        setMeth   = 'TRUE'
        getMeth   = 'TRUE' />

      

    </class>
  </package>
</gdd>
