=== ibab/lhcb-software/LHCb/Event/TrackEvent/xml/gdd.dtd
<?xml encoding="UTF-8"?>
<!-- ?xml encoding="ISO-8859-1"? -->
<!ELEMENT gdd ((import*, package+)+)>
<!ATTLIST gdd
        version          CDATA                             "1.0"
>
<!ELEMENT import EMPTY>
<!ATTLIST import
        name             CDATA                             #REQUIRED
        std              (TRUE | FALSE)                    "FALSE"
        soft             (TRUE | FALSE)                    "FALSE"
        ignore           (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT package ((import*, class*, namespace*, assoc*)*)>
<!ATTLIST package
        name             CDATA                             #REQUIRED
>
<!-- ELEMENT class ((class?, ..... -->
<!ELEMENT class ((desc?, base?, import?, location?, enum?, typedef?, constructor?, destructor?, method?, attribute?, relation?, template?)*)>
<!-- candidates 4 deprication: filename, templateVector, templateList, serializers -->
<!ATTLIST class
        name              CDATA                            #REQUIRED
        author            CDATA                            #REQUIRED
        desc              CDATA                            #REQUIRED
        filename          CDATA                            #IMPLIED  
        id                CDATA                            #IMPLIED
        version           CDATA                            #IMPLIED
        location          CDATA                            #IMPLIED
        stdVectorTypeDef  (TRUE | FALSE)                   "FALSE"  
        keyedContTypeDef  (TRUE | FALSE)                   "FALSE"  
	contObjectTypeDef (TRUE | FALSE)                   "FALSE"
        templateVector    (TRUE | FALSE)                   "TRUE"    
        templateList      (TRUE | FALSE)                   "TRUE"    
        serializers       (TRUE | FALSE)                   "TRUE"    
>       
<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc
        xml:space        (default | preserve)              #FIXED "preserve"
>
<!ELEMENT location EMPTY>
<!ATTLIST location
        name             CDATA                             #REQUIRED
        place            CDATA                             #REQUIRED
        noQuote          (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT namespace ((desc?, typedef?, enum?, class?, import?, attribute?, method?)*)>
<!ATTLIST namespace
        name             CDATA                             #REQUIRED
        author           CDATA                             #IMPLIED
        desc             CDATA                             #REQUIRED
>
<!ELEMENT base EMPTY>
<!ATTLIST base
        name             CDATA                             #REQUIRED
        virtual          (TRUE | FALSE)                    "FALSE"
        access           (PUBLIC | PROTECTED | PRIVATE)    "PUBLIC"
>
<!ELEMENT enum EMPTY>
<!ATTLIST enum
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        value            CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
>
<!ELEMENT typedef EMPTY>
<!ATTLIST typedef 
        desc             CDATA                             #REQUIRED
        type             CDATA                             #REQUIRED
        def              CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
>
<!ELEMENT constructor (arg*, code?, arg*)>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST constructor
        desc             CDATA                             #REQUIRED
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED   
        initList         CDATA                             #IMPLIED
        explicit         (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT destructor (arg*, code?, arg*)>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST destructor
        desc             CDATA                             #REQUIRED
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED  
>
<!ELEMENT method ((arg*, return?, arg*, code?, arg*) | (arg*, code?, arg*, return?, arg*))>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST method
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        template         CDATA                             #IMPLIED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PUBLIC"
        const            (TRUE | FALSE)                    "FALSE"
        virtual          (TRUE | FALSE | PURE)             "FALSE"
        static           (TRUE | FALSE)                    "FALSE"
        inline           (TRUE | FALSE)                    "FALSE"
        friend           (TRUE | FALSE)                    "FALSE"
        type             CDATA                             "void"
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED  
>
<!ELEMENT arg EMPTY>
<!ATTLIST arg
        type             CDATA                             #REQUIRED
        name             CDATA                             #IMPLIED
        const            (TRUE | FALSE)                    "FALSE"
        inout            (BYVALUE | INPUT | INOUT | BOTH)  "INPUT"
>
<!ELEMENT return EMPTY>
<!ATTLIST return
        type             CDATA                             #REQUIRED
        const            (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
        xml:space        (default | preserve)              #FIXED "preserve"
>
<!ELEMENT attribute (bitfield*)>
<!-- candidates 4 deprication: array, serialize -->
<!ATTLIST attribute
        type             CDATA                             #REQUIRED
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        init             CDATA                             #IMPLIED
        dictalias        CDATA                             #IMPLIED
        array            CDATA                             "FALSE"    
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
        compression      (TRUE | FALSE)                    "TRUE"
        serialize        (TRUE | FALSE)                    "TRUE"     
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        transient        (TRUE | FALSE)                    "FALSE"    
>
<!ELEMENT relation EMPTY>
<!ATTLIST relation
        type             CDATA                             #REQUIRED
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
        multiplicity     (1 | N | n | M | m)               "1"
        serialize        (TRUE | FALSE)                    "TRUE"
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        addMeth          (TRUE | FALSE)                    "TRUE"
        remMeth          (TRUE | FALSE)                    "TRUE"
        clrMeth          (TRUE | FALSE)                    "TRUE"
>
<!ELEMENT bitfield EMPTY>
<!ATTLIST bitfield
        name             CDATA                             #REQUIRED
        type             CDATA                             #IMPLIED
        length           CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        startBit         CDATA                             #IMPLIED
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        checkMeth        (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT template EMPTY>
<!ATTLIST template
        name             CDATA                             #REQUIRED
        t1               CDATA                             "THIS"
        t2               CDATA                             #IMPLIED
        t3               CDATA                             #IMPLIED
        t4               CDATA                             #IMPLIED
>

<!ELEMENT assoc EMPTY>
<!ATTLIST assoc
        type             (1D | 2D)                         "1D"
        weight           CDATA                             "NONE"
        from             CDATA                             #REQUIRED
        to               CDATA                             #REQUIRED
>

<!ENTITY KeyedObjectKey 'int'>
<!ENTITY Reference '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>'
>
<!ENTITY StlVector '<template name="VectorDict" t1="THIS"/>'
>
<!ENTITY StlPtrVector '<template name="VectorDict" t1="THIS*"/>'
>
<!ENTITY DataObject '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>'
>
<!ENTITY ContainedObject '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>'
>
<!ENTITY KeyedContainer '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>
        <template name="KeyedContainerDict"/>'
>
<!ENTITY KeyedObject '<template name="KeyedObjectDict" t1="int"/>
        <template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>
        <template name="KeyedContainerDict"/>'
>

=== ibab/lhcb-software/Rec/Rich/RichRecBase/xml/RichRecPixelOnRing.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>
<package name="RichRecBase">

<!-- **************************************************************************
  * $Id: RichRecPixelOnRing.xml,v 1.2 2006-08-09 11:05:04 jonrob Exp $
  *****************************************************************************
  * XML-description of RichRecPixelOnRing class                               *
  * author: Chris Jones   Christopher.Rob.Jones@cern.ch                       *
  * date:   2006/08/03                                                        *
  ************************************************************************* -->


<class 
        name             = "RichRecPixelOnRing"
        virtual          = "FALSE"
        author           = "Chris Jones   (Christopher.Rob.Jones@cern.ch)" 
        desc             = "Ultility class to represent the association of a RichRecPixel to a RichRecRing" >

        <import name="Event/RichRecPixel"   soft="TRUE" />

 	<typedef 
		desc   = "typedef for std::vector of RichRecPixelOnRing" 
		access = "PUBLIC" 
		def    = "Vector" 
		type   = "std::vector&lt;RichRecPixelOnRing&gt;"
	/>

        <constructor 
                desc     = "Constructor from pixel and probability value" 
                initList = "m_pixel(pPix), m_associationProb(prob)">
                <arg const="FALSE" inout="BYVALUE" name="pPix" type="LHCb::RichRecPixel*"/>
                <arg const="TRUE"  inout="BYVALUE" name="prob" type="double"/>
                <code/>
        </constructor>
 
        <attribute 
                compression = "FALSE" 
                desc        = "RichRecPixel associated to the parent RichRecRing" 
                init        = "nullptr" 
                name        = "pixel" 
                type        = "LHCb::RichRecPixel*"
                nonconstaccessor = "TRUE"
        />

        <attribute 
                compression = "FALSE" 
                desc        = "The probability of the RichRecPixel association to the parent RichRecRing" 
                init        = "0" 
                name        = "associationProb" 
                type        = "double"
        />

</class>

</package>
</gdd>

=== ibab/lhcb-software/Rec/Rich/RichRecBase/xml/RichRecRingOnPixel.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>
<package name="RichRecBase">

<!-- **************************************************************************
  * $Id: RichRecRingOnPixel.xml,v 1.2 2006-08-09 11:05:04 jonrob Exp $
  *****************************************************************************
  * XML-description of RichRecRingOnPixel class                               *
  * author: Chris Jones   Christopher.Rob.Jones@cern.ch                       *
  * date:   2006/08/03                                                        *
  ************************************************************************* -->


<class 
        name             = "RichRecRingOnPixel" 
        virtual          = "FALSE"
        author           = "Chris Jones   (Christopher.Rob.Jones@cern.ch)" 
        desc             = "Ultility class to represent the association of a RichRecRing to a RichRecPixel" >

        <import name="Event/RichRecRing" soft="TRUE" />

	<typedef 
		desc   = "typedef for std::vector of RichRecRingOnPixel" 
		access = "PUBLIC" 
		def    = "Vector" 
		type   = "std::vector&lt;RichRecRingOnPixel&gt;"
	/>
 
        <constructor 
                desc     = "Constructor from ring and probability value" 
                initList = "m_ring(pRing), m_associationProb(prob)">
                <arg const="FALSE" inout="BYVALUE" name="pRing" type="LHCb::RichRecRing*"/>
                <arg const="TRUE"  inout="BYVALUE" name="prob" type="double"/>
                <code/>
        </constructor>

        <attribute 
                compression = "FALSE" 
                desc        = "RichRecRing associated to the parent RichRecPixel" 
                init        = "nullptr" 
                name        = "ring" 
                type        = "LHCb::RichRecRing*"
                nonconstaccessor = "TRUE"
        />

        <attribute 
                compression = "FALSE" 
                desc        = "The probability of the RingRecRing association to the parent RichRecPixel" 
                init        = "0" 
                name        = "associationProb" 
                type        = "double"
        />

</class>

</package>
</gdd>

=== ibab/lhcb-software/Rec/Tr/TrackFitEvent/xml/VeloLiteMeasurement.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name='TrackFitEvent'>

<!-- =============== VeloLiteMeasurement class definition =============== -->

    <class
      name        = 'VeloLiteMeasurement'
      author      = 'David Hutchcroft'
      desc        = 'Base class for a measurement made from a VeloLiteCluster.'
      serializers = 'FALSE'>

      <base name='LHCb::Measurement' />

      <import name='Event/Measurement' />
      <import name='Event/VeloCluster' />

      <constructor
        desc = 'Constructor'
               argList = ' LHCb::Measurement::Type&amp; type, LHCb::VeloLiteCluster cluster'
        initList = ' Measurement(type, LHCbID(cluster.channelID())), m_cluster(&amp;cluster)'> 
      </constructor>

      <attribute
        type = 'const LHCb::VeloLiteCluster*'
        name = 'cluster'
        desc = 'Pointer to the VeloLiteCluster'
	getMeth = 'FALSE'
        setMeth = 'FALSE'  />

      <method
        type  = 'const LHCb::VeloLiteCluster*'
        name  = 'cluster'
        desc  = 'Retrieve const  Pointer to the VeloLiteCluster'
        const = 'TRUE'>
        <code>
  return m_cluster;
        </code>
      </method>


      <method
	type    = 'LHCb::VeloChannelID'
	name    = 'channelID'
	desc    = 'channel identifier'
	const   = 'TRUE'>
	<code>
     return m_cluster->channelID() ;
        </code>
      </method>

      <method
	type    = 'bool'
	name    = 'highThreshold'
	desc    = 'has high Threshold'
	const   = 'TRUE'>
	<code>
      return m_cluster->highThreshold() ;
        </code>
      </method>
      
      <method
	type    = 'unsigned int'
	name    = 'size'
	desc    = 'cluster size'
	const   = 'TRUE'>
	<code>
     return m_cluster->pseudoSize();
        </code>
      </method>

    </class>

  </package>
</gdd>

=== ibab/lhcb-software/Rec/Rich/RichRecBase/xml/RichRecPointOnRing.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>
<package name="RichRecBase">

<!-- **************************************************************************
  * $Id: RichRecPointOnRing.xml,v 1.4 2008-02-15 10:08:47 jonrob Exp $
  *****************************************************************************
  * XML-description of RichRecPointOnRing class                               *
  * author: Chris Jones   Christopher.Rob.Jones@cern.ch                       *
  * date:   2006/08/03                                                        *
  ************************************************************************* -->


<class 
        name        = "RichRecPointOnRing" 
        author      = "Chris Jones   (Christopher.Rob.Jones@cern.ch)" 
        desc        = "Ultility class to represent a point on a Cherenkov Ring" 
        virtual     = "FALSE" >

        <import name="GaudiKernel/Point3DTypes.h"/>
        <import name="Kernel/RichSmartID.h"/>
        <import name="RichDet/DeRichSphMirror.h"/>

        <enum name="Acceptance" desc="Describes the how this position lies in the RICH acceptance" access="PUBLIC" >
          <enumval name="UndefinedAcceptance" value="0" desc="The acceptance is undefined"/>
          <enumval name="OutsideHPDPanel"     value="1" desc="Point is outside the general HPD panel acceptance"/>
          <enumval name="InHPDPanel"          value="2" desc="Point is inside the acceptance of the HPD panels"/>
          <enumval name="InHPDTube"           value="3" desc="Point is inside the acceptance of singe HPD tube"/>
        </enum>

        <constructor 
                desc     = "Constructor from global position, location position, acceptance flag and RichSmartID" 
                initList = "m_globalPosition(gPos), m_localPosition(lPos), m_azimuth(azimuth), m_smartID(id), m_acceptance(acc), m_primaryMirror(const_cast&lt;DeRichSphMirror*&gt;(primMirr)), m_secondaryMirror(const_cast&lt;DeRichSphMirror*&gt;(secMirr))">
                <arg const="TRUE"                  name="gPos" type="Gaudi::XYZPoint"/>
                <arg const="TRUE"                  name="lPos" type="Gaudi::XYZPoint"/>
                <arg const="TRUE"  inout="BYVALUE" name="id = LHCb::RichSmartID()" type="LHCb::RichSmartID"/>
                <arg const="TRUE"  inout="BYVALUE" name="acc = LHCb::RichRecPointOnRing::UndefinedAcceptance"  type="LHCb::RichRecPointOnRing::Acceptance"/>
                <arg const="TRUE"                  name="primMirr = nullptr" type="DeRichSphMirror*"/>
                <arg const="TRUE"                  name="secMirr = nullptr"  type="DeRichSphMirror*"/>
                <arg const="TRUE"  inout="BYVALUE" name="azimuth = -1" type="float"/>
                <!--arg const="TRUE"  inout="BYVALUE" name="radius = -1"  type="float"/-->
                <code>
                </code>
        </constructor>

        <attribute 
                desc = "Position on the ring in global coordinates" 
                name = "globalPosition" 
                type = "Gaudi::XYZPoint"
                init = "0,0,0"
        />

        <attribute 
                desc = "Position on the ring in local coordinates" 
                name = "localPosition" 
                type = "Gaudi::XYZPoint"
                init = "0,0,0"
        />  

        <attribute 
                desc = "Azimuthal phi w.r.t the ring centre for this position" 
                name = "azimuth" 
                type = "float"
                init = "-1"
        />

        <!--attribute 
                desc = "Radius w.r.t the ring centre for this position" 
                name = "radius" 
                type = "float"
                init = "-1"
        /-->  

        <attribute 
                desc = "RichSmartID identifying the HPD or pixel this point is in, if known" 
                name = "smartID" 
                type = "LHCb::RichSmartID"
        />  

        <attribute 
                desc = "The RICH acceptance state of the point" 
                name = "acceptance" 
                type = "LHCb::RichRecPointOnRing::Acceptance"
                init = "LHCb::RichRecPointOnRing::UndefinedAcceptance"
        />

	<typedef 
		desc   = "typedef for std::vector of RichRecPointOnRing" 
		access = "PUBLIC" 
		def    = "Vector" 
		type   = "std::vector&lt;RichRecPointOnRing&gt;"
	/>

        <attribute 
                desc = "Pointer to the associated DeRichSphMirror object for the primary mirror" 
                name = "primaryMirror" 
                type = "DeRichSphMirror*"
                init = "nullptr"
        />

        <attribute 
                desc = "Pointer to the associated DeRichSphMirror object for the secondary mirror" 
                name = "secondaryMirror" 
                type = "DeRichSphMirror*"
                init = "nullptr"
        />
   
</class>

</package>
</gdd>

=== ibab/lhcb-software/LHCb/Event/TrackEvent/xml/Measurement.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE gdd SYSTEM 'gdd.dtd'>
<gdd>
  <package name='TrackEvent'>

<!-- ================= Measurement class definition ================= -->

    <class
      name        = 'Measurement'
      author      = 'Jose Hernando, Eduardo Rodrigues'
      desc        = 'Measurement is the base class for offline and online measurements.'
      stdVectorTypeDef = "TRUE"
      serializers = 'FALSE' >

      <import name='Event/TrackTypes.h' />
      <import name='Event/StateVector.h' />
      <import name='Kernel/LHCbID' />
      <import name='Kernel/Trajectory' />
      <import name='DetDesc/DetectorElement' soft='FORWARDONLY' namespace = '::'/>

      &StlPtrVector;

<!--
  /** Measurement type enumerations
   *
   *   Unknown  : measurement of undefined type (this should never happen!)
   *   VeloR    : Velo-R measurement
   *   VeloPhi  : Velo-phi measurement
   *   TT       : TT measurement (ST measurement in the TT stations)
   *   IT       : IT measurement (ST measurement in the IT seeding stations)
   *   OT       : OT measurement in the seeding stations
   *   Muon     : Muon measurement
   *   VP       : VP x,y measurement
   *   UT       : UT measurement
   *
   */
-->
      <enum
        name    = 'Type'
        value   = 'Unknown,VeloR,VeloPhi,VeloLiteR,VeloLitePhi,TT,IT,OT,Muon, TTLite, ITLite,VP,Calo,Origin,FT,UT=19,UTLite'
        desc    = 'enumerator for the type of Measurement'
        access  = 'PUBLIC'
        strTypConv = 'TRUE' 
      />

      <constructor 
	desc     = "Copy constructor" 
	argList  = "LHCb::Measurement other" 
        initList = "m_mtype(other.m_mtype),m_z(other.m_z),m_measure(other.m_measure),m_errMeasure(other.m_errMeasure),m_lhcbID(other.m_lhcbID),m_detectorElement(other.m_detectorElement)" >
        <code>
	  if( other.m_trajectory )
            m_trajectory.reset( other.m_trajectory->clone().release() );
	</code>
      </constructor>

      <constructor 
	desc     = "Constructor" 
	argList  = "const LHCb::Measurement::Type type, const LHCb::LHCbID id, const DetectorElement* elem=0"
        initList = "m_mtype(type), m_z(0), m_measure(0), m_errMeasure(0), m_lhcbID(id), m_detectorElement(elem)" >
      </constructor>

     <attribute
       type    = 'bitfield'
       name    = 'mtype'
       desc    = 'the variety of measurement types'
       getMeth = 'FALSE'
       setMeth = 'FALSE'
       access  = 'PROTECTED'>
       <bitfield
         name      = 'type'
         length    = '6'
         type      = 'Type'
         getMeth   = 'FALSE'
         setMeth   = 'TRUE'
         checkMeth = 'FALSE'
         desc      = 'measurement type' />
      </attribute>

      <attribute
        type    = 'double'
        name    = 'z'
        desc    = 'the z-position of the measurement'
        access  = 'PROTECTED' />

      <attribute
        type    = 'double'
        name    = 'measure'
        desc    = 'the measurement value'
        access  = 'PROTECTED' />

      <attribute
        type    = 'double'
        name    = 'errMeasure'
        desc    = 'the measurement error'
        access  = 'PROTECTED' />

      <attribute
        type    = 'std::unique_ptr &lt; LHCb::Trajectory &gt;'
        name    = 'trajectory'
        desc    = 'the trajectory representing the measurement (owner)'
        access  = 'PROTECTED'
        getMeth = 'FALSE'
        setMeth = 'FALSE' />

      <attribute
        type    = 'LHCb::LHCbID'
        name    = 'lhcbID'
        desc    = 'the corresponding LHCbID'
        access  = 'PROTECTED' />

      <attribute
        type    = 'const DetectorElement*'
        name    = 'detectorElement'
        desc    = 'the corresponding detectorElement'
	setMeth = 'FALSE'
	getMeth = 'TRUE'
	transient = 'TRUE'
        access  = 'PROTECTED' />

      <method
        type    = 'double'
        name    = 'errMeasure2'
        desc    = 'Retrieve const  the measurement error squared'
        const   = 'TRUE'>
        <code>
  return m_errMeasure * m_errMeasure;
        </code>
      </method>

      <method
        type    = 'double'
        name    = 'resolution'
        argList = 'Gaudi::XYZPoint /*point*/, Gaudi::XYZVector /*vec*/'
        desc    = 'Retrieve the measurement error'
        const   = 'TRUE'
        virtual = 'TRUE'>
        <code>
  return m_errMeasure;
        </code>
      </method>

      <method
        type    = 'double'
        name    = 'resolution2'
        argList = 'Gaudi::XYZPoint /*point*/, Gaudi::XYZVector /*vec*/'
        desc    = 'Retrieve the measurement error squared'
        const   = 'TRUE'
        virtual = 'TRUE'>
        <code>
  return m_errMeasure * m_errMeasure;
        </code>
      </method>

      <method
        type    = 'LHCb::Measurement::Type'
        name    = 'type'
        desc    = 'Retrieve the measurement type'
        const   = 'TRUE'>
        <code>
  return (Measurement::Type)((m_mtype &amp; typeMask) &gt;&gt; typeBits);
        </code>
      </method>

      <method
        type    = 'bool'
        name    = 'checkType'
        argList = 'LHCb::Measurement::Type value'
        desc    = 'Check the measurement type'
        const   = 'TRUE'>
        <code>
  return type() == value;
        </code>
      </method>

      <method
        type    = 'LHCb::Measurement*'
        name    = 'clone'
        desc    = 'Clone the measurement'
        const   = 'TRUE'
        virtual = 'PURE'>
      </method>

      <method
        type    = 'const LHCb::Trajectory&amp;'
        name    = 'trajectory'
        desc    = 'Retrieve the trajectory representing the measurement'
        const   = 'TRUE'>
        <code>
  return *m_trajectory;
        </code>
      </method>

      <method
        name    = 'setTrajectory'
        desc    = 'Set the trajectory'>
        <arg type = 'std::unique_ptr &lt; LHCb::Trajectory &gt;' name='traj' const='FALSE'/>
        <code>  m_trajectory = std::move(traj) ; </code>
      </method>
      
    </class>

  </package>
</gdd>
