=== ibab/lhcb-software/LHCb/Event/TrackEvent/xml/gdd.dtd
<?xml encoding="UTF-8"?>
<!-- ?xml encoding="ISO-8859-1"? -->
<!ELEMENT gdd ((import*, package+)+)>
<!ATTLIST gdd
        version          CDATA                             "1.0"
>
<!ELEMENT import EMPTY>
<!ATTLIST import
        name             CDATA                             #REQUIRED
        std              (TRUE | FALSE)                    "FALSE"
        soft             (TRUE | FALSE)                    "FALSE"
        ignore           (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT package ((import*, class*, namespace*, assoc*)*)>
<!ATTLIST package
        name             CDATA                             #REQUIRED
>
<!-- ELEMENT class ((class?, ..... -->
<!ELEMENT class ((desc?, base?, import?, location?, enum?, typedef?, constructor?, destructor?, method?, attribute?, relation?, template?)*)>
<!-- candidates 4 deprication: filename, templateVector, templateList, serializers -->
<!ATTLIST class
        name              CDATA                            #REQUIRED
        author            CDATA                            #REQUIRED
        desc              CDATA                            #REQUIRED
        filename          CDATA                            #IMPLIED  
        id                CDATA                            #IMPLIED
        version           CDATA                            #IMPLIED
        location          CDATA                            #IMPLIED
        stdVectorTypeDef  (TRUE | FALSE)                   "FALSE"  
        keyedContTypeDef  (TRUE | FALSE)                   "FALSE"  
	contObjectTypeDef (TRUE | FALSE)                   "FALSE"
        templateVector    (TRUE | FALSE)                   "TRUE"    
        templateList      (TRUE | FALSE)                   "TRUE"    
        serializers       (TRUE | FALSE)                   "TRUE"    
>       
<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc
        xml:space        (default | preserve)              #FIXED "preserve"
>
<!ELEMENT location EMPTY>
<!ATTLIST location
        name             CDATA                             #REQUIRED
        place            CDATA                             #REQUIRED
        noQuote          (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT namespace ((desc?, typedef?, enum?, class?, import?, attribute?, method?)*)>
<!ATTLIST namespace
        name             CDATA                             #REQUIRED
        author           CDATA                             #IMPLIED
        desc             CDATA                             #REQUIRED
>
<!ELEMENT base EMPTY>
<!ATTLIST base
        name             CDATA                             #REQUIRED
        virtual          (TRUE | FALSE)                    "FALSE"
        access           (PUBLIC | PROTECTED | PRIVATE)    "PUBLIC"
>
<!ELEMENT enum EMPTY>
<!ATTLIST enum
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        value            CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
>
<!ELEMENT typedef EMPTY>
<!ATTLIST typedef 
        desc             CDATA                             #REQUIRED
        type             CDATA                             #REQUIRED
        def              CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
>
<!ELEMENT constructor (arg*, code?, arg*)>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST constructor
        desc             CDATA                             #REQUIRED
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED   
        initList         CDATA                             #IMPLIED
        explicit         (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT destructor (arg*, code?, arg*)>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST destructor
        desc             CDATA                             #REQUIRED
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED  
>
<!ELEMENT method ((arg*, return?, arg*, code?, arg*) | (arg*, code?, arg*, return?, arg*))>
<!-- candidates 4 deprication: argInOut -->
<!ATTLIST method
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        template         CDATA                             #IMPLIED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PUBLIC"
        const            (TRUE | FALSE)                    "FALSE"
        virtual          (TRUE | FALSE | PURE)             "FALSE"
        static           (TRUE | FALSE)                    "FALSE"
        inline           (TRUE | FALSE)                    "FALSE"
        friend           (TRUE | FALSE)                    "FALSE"
        type             CDATA                             "void"
        argList          CDATA                             #IMPLIED
        argInOut         CDATA                             #IMPLIED  
>
<!ELEMENT arg EMPTY>
<!ATTLIST arg
        type             CDATA                             #REQUIRED
        name             CDATA                             #IMPLIED
        const            (TRUE | FALSE)                    "FALSE"
        inout            (BYVALUE | INPUT | INOUT | BOTH)  "INPUT"
>
<!ELEMENT return EMPTY>
<!ATTLIST return
        type             CDATA                             #REQUIRED
        const            (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
        xml:space        (default | preserve)              #FIXED "preserve"
>
<!ELEMENT attribute (bitfield*)>
<!-- candidates 4 deprication: array, serialize -->
<!ATTLIST attribute
        type             CDATA                             #REQUIRED
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        init             CDATA                             #IMPLIED
        dictalias        CDATA                             #IMPLIED
        array            CDATA                             "FALSE"    
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
        compression      (TRUE | FALSE)                    "TRUE"
        serialize        (TRUE | FALSE)                    "TRUE"     
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        transient        (TRUE | FALSE)                    "FALSE"    
>
<!ELEMENT relation EMPTY>
<!ATTLIST relation
        type             CDATA                             #REQUIRED
        name             CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        access           (PUBLIC | PROTECTED | PRIVATE)    "PRIVATE"
        multiplicity     (1 | N | n | M | m)               "1"
        serialize        (TRUE | FALSE)                    "TRUE"
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        addMeth          (TRUE | FALSE)                    "TRUE"
        remMeth          (TRUE | FALSE)                    "TRUE"
        clrMeth          (TRUE | FALSE)                    "TRUE"
>
<!ELEMENT bitfield EMPTY>
<!ATTLIST bitfield
        name             CDATA                             #REQUIRED
        type             CDATA                             #IMPLIED
        length           CDATA                             #REQUIRED
        desc             CDATA                             #REQUIRED
        startBit         CDATA                             #IMPLIED
        setMeth          (TRUE | FALSE)                    "TRUE"
        getMeth          (TRUE | FALSE)                    "TRUE"
        checkMeth        (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT template EMPTY>
<!ATTLIST template
        name             CDATA                             #REQUIRED
        t1               CDATA                             "THIS"
        t2               CDATA                             #IMPLIED
        t3               CDATA                             #IMPLIED
        t4               CDATA                             #IMPLIED
>

<!ELEMENT assoc EMPTY>
<!ATTLIST assoc
        type             (1D | 2D)                         "1D"
        weight           CDATA                             "NONE"
        from             CDATA                             #REQUIRED
        to               CDATA                             #REQUIRED
>

<!ENTITY KeyedObjectKey 'int'>
<!ENTITY Reference '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>'
>
<!ENTITY StlVector '<template name="VectorDict" t1="THIS"/>'
>
<!ENTITY StlPtrVector '<template name="VectorDict" t1="THIS*"/>'
>
<!ENTITY DataObject '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>'
>
<!ENTITY ContainedObject '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>'
>
<!ENTITY KeyedContainer '<template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>
        <template name="KeyedContainerDict"/>'
>
<!ENTITY KeyedObject '<template name="KeyedObjectDict" t1="int"/>
        <template name="SmartRefDict"/>
        <template name="SmartRefVectorDict"/>
        <template name="VectorDict" t1="THIS*"/>
        <template name="ObjectVectorDict"/>
        <template name="KeyedContainerDict"/>'
>

=== ibab/lhcb-software/LHCb/Event/DigiEvent/xml/VeloPixLiteCluster.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--- $Id: -->
<!--- Author  : Victor Coco Victor.Coco@cern.ch-->
<!--- Created : 2009-11-13 -->
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>

<!--- IF YOU PLAN TO MODIFY THE BITFIELD, PLEASE READ CAREFULLY THE FINAL COMMENT -->

<package name="DigiEvent">
    <class name="VeloPixLiteCluster" 
     author="V. Coco" 
     desc="A cluster as might be produced by the TELL40 but without the full information"
     location="Raw/VP/LiteClusters"
     serializers="FALSE"
    >

    <import name="Kernel/VeloPixChannelID"/>
    <import name="Kernel/FastClusterContainer"/>
    <import name="Kernel/SiDataFunctor"/>
    <import name="LHCbMath/LHCbMath"/>
 
    <typedef desc = "channelID type"
       type =  "LHCb::VeloPixChannelID"
       def = "chan_type"
       access = "PUBLIC " />

    <typedef desc = "fast container for light clusters"
       type =  "FastClusterContainer &lt; LHCb::VeloPixLiteCluster, ulonglong &gt;"
       def = "VeloPixLiteClusters"
       access = "PUBLIC " />


     <typedef desc = "finding policy"
       type =  "SiDataFunctor::CompareByChannel &lt; LHCb::VeloPixLiteCluster&gt;"
       def = "findPolicy"
       access = "PUBLIC " /> 

     <constructor desc="Constructor" 
       argList='VeloPixChannelID &amp; chan,  unsigned int ToT , std::pair&lt;double,double&gt; fracPix, bool longPix'>
       <code>

 unsigned int tFracX = (LHCb::Math::round(fracPix.first * (1 &lt;&lt;( interPixelFractionYBits-interPixelFractionXBits))));
 unsigned int tFracY = (LHCb::Math::round(fracPix.second *(1 &lt;&lt; (interPixelFractionYBits-interPixelFractionXBits))));
 unsigned int tlongPix;
 longPix == true  ? tlongPix = 1:   tlongPix= 0;

 m_liteCluster = (((ulonglong)chan) &lt;&lt; channelIDBits) + 
                 (((ulonglong)ToT) &lt;&lt; clustToTBits) +
                 (((ulonglong)tFracX) &lt;&lt; interPixelFractionXBits) +
                 (((ulonglong)tFracY) &lt;&lt; interPixelFractionYBits) +
                 (((ulonglong)tlongPix) &lt;&lt; longPixBits)
                 ;
       </code>
      </constructor>


    <constructor desc="Constructor" 
       argList='VeloPixChannelID &amp; chan ,unsigned int ToT,
                std::pair&lt;unsigned int,unsigned int&gt; fracPixel, bool longPix'>
       <code>

 unsigned int tlongPix;
 longPix == true  ? tlongPix = 1:   tlongPix= 0;
 m_liteCluster = (((ulonglong)chan) &lt;&lt; channelIDBits) +
                 (((ulonglong)ToT) &lt;&lt; clustToTBits) +
                 (((ulonglong)fracPixel.first) &lt;&lt; interPixelFractionXBits) +
                 (((ulonglong)fracPixel.second) &lt;&lt; interPixelFractionYBits) +
                 (((ulonglong)tlongPix) &lt;&lt; longPixBits)
          ;
       </code>
      </constructor>



     <destructor  desc="destructor">
     <code>
     //
     </code>
     </destructor>

     <method type='LHCb::VeloPixLiteCluster &amp;' 
             name='operator ='
             argList='const VeloPixLiteCluster &amp; c'  
             const='FALSE'  desc='equal'>
        <code>m_liteCluster = c.m_liteCluster; 
              return *this; </code>
     </method>

     <method
      name="interPixelFraction"
      type="std::pair&lt;double,double&gt;"
      desc="fractionnal positions within a pixel"
      const="TRUE">
     <code>
 std::pair&lt;unsigned int,unsigned int&gt; fracUnit = fractionUnits();
 std::pair&lt;double,double&gt; frac(double(fracUnit.first)/double((1 &lt;&lt; (interPixelFractionYBits-interPixelFractionXBits))),
  double(fracUnit.second)/double((1 &lt;&lt;(interPixelFractionYBits-interPixelFractionXBits) )));
 return frac;
     </code>
     </method>


     <method
      name="interPixelFractionX"
      type="double"
      desc="fractionnal X position within a pixel"
      const="TRUE">
     <code>
return  double(fractionUnitsX())/double((1 &lt;&lt;( interPixelFractionYBits-interPixelFractionXBits)));
     </code>
     </method>

     <method
      name="clustToT"
      type="unsigned int"
      desc="clustToT of the cluster"
      const="TRUE">
     <code>
return (unsigned int)((m_liteCluster &amp;0x70000000LL ) &gt;&gt; clustToTBits );
     </code>
     </method>


     <method
      name="interPixelFractionY"
      type="double"
      desc="fractionnal Y position within a pixel"
      const="TRUE">
     <code>
return  double(fractionUnitsY())/double((1 &lt;&lt;( interPixelFractionYBits-interPixelFractionXBits)));
     </code>
     </method>


     <method
      name="isLongPixel"
      type="bool"
      desc="is it an long pixel"
      const="TRUE">
     <code>
  return (((m_liteCluster &amp; (ulonglong)0x80000000LL) &gt;&gt; longPixBits) == 1);
     </code>
     </method>

      <method
      access="PRIVATE"
      name="fractionUnits"
      type="std::pair&lt;unsigned int,unsigned int&gt;"
      desc="pair of numbers between 0 and  /8ths of the x and y size of a pixel"
      const="TRUE"
      >
      <code> 
std::pair&lt;unsigned int,unsigned int&gt; fracUnit ((unsigned int)((m_liteCluster &amp; (ulonglong)0x700000000LL) &gt;&gt; interPixelFractionXBits),(unsigned int)((m_liteCluster &amp; (ulonglong)0x3800000000LL) &gt;&gt; interPixelFractionYBits)); 
return fracUnit;
     </code>
     </method>

      <method
      access="PRIVATE"
      name="fractionUnitsX"
      type="unsigned int"
      desc="number between 0 and  /8ths of the x size of a pixel"
      const="TRUE"
      >
      <code> 

return (unsigned int)((m_liteCluster &amp; (ulonglong)0x700000000LL) &gt;&gt; interPixelFractionXBits);
     </code>
     </method>

      <method
      access="PRIVATE"
      name="fractionUnitsY"
      type="unsigned int"
      desc="number between 0 and  /8ths of the y size of a pixel"
      const="TRUE"
      >
      <code> 

return (unsigned int)((m_liteCluster &amp; (ulonglong)0x3800000000LL) &gt;&gt; interPixelFractionYBits);
     </code>
     </method>

      <method
      access="PUBLIC"
      name="channelID"
      type="LHCb::VeloPixChannelID"
      desc="The Channel"
      const="TRUE"
      >
      <code> return VeloPixChannelID((unsigned int)((m_liteCluster &amp; 0xfffffffLL) &gt;&gt; channelIDBits)); 
     </code>
     </method>


     <attribute type='ulonglong' name='liteCluster' setMeth="FALSE" getMeth="FALSE" desc='the lite Cluster' init='0x0LL'/>

     <enum name='liteClusterBits' desc='position of the first bit of a given field'>
       <enumval name = 'channelIDBits' value = '0' desc='the channelID field 1st bit position'/>
       <enumval name = 'clustToTBits' value = '28' desc='the clustToT field 1st bit position'/>
       <enumval name = 'longPixBits' value = '31' desc='the longPix field 1st bit position'/>
       <enumval name = 'interPixelFractionXBits' value = '32' desc='the interPixelFractionX field 1st bit position'/>
       <enumval name = 'interPixelFractionYBits' value = '35' desc='the interPixelFractionY field 1st bit position'/>
     </enum>  

<!--- First attempt was using enum also for filed mask, BUT this creates some warning (and probably errors) under win32 -->
<!--- Since it does not recognise 64bits interger as underlying type (seams to be a known feature of win32 compiler)    -->

<!--- #     <enum name='liteClusterMask' desc='the given field mask'> -->
<!--- #       <enumval name = 'channelIDMask' value = '0xfffffffLL' desc='the channelID field mask'/> -->
<!--- #       <enumval name = 'clustToTMask' value = '0x70000000LL' desc='the clustToTMask field mask'/> -->
<!--- #       <enumval name = 'longPixMask' value = '0x80000000LL' desc='the longPixMask field mask'/> -->
<!--- #       <enumval name = 'interPixelFractionXMask' value = '0x700000000LL' desc='the interPixelFractionXMask field mask'/> -->
<!--- #       <enumval name = 'interPixelFractionYMask' value = '0x3800000000LL' desc='the interPixelFractionYMask field mask'/> -->
<!--- #     </enum>       -->  


<!--- Second attempt was to declare the mask fields as single attributes of type ulonglong. It solve the win32 problems    -->
<!--- BUT the size of the class goes from 8 to 48 (8 for each ulonglong) causing runtime error in the constructor of FastClusterContainer -->
<!--- since sizeof(ulonglong)!=sizeof(VeloPixLiteCluster) -->

<!--- #    <attribute type='ulonglong' name='channelIDMask' setMeth="FALSE" getMeth="FALSE" desc='the channelID field mask' init='0xfffffffLL'/>-->
<!--- #    <attribute type='ulonglong' name='clustToTMask' setMeth="FALSE" getMeth="FALSE" desc='the clustToTMask field mask' init='0x70000000LL'/>-->
<!--- #    <attribute type='ulonglong' name='longPixMask' setMeth="FALSE" getMeth="FALSE" desc='the longPixMask field mask' init='0x80000000LL'/>-->
<!--- #    <attribute type='ulonglong' name='interPixelFractionXMask' setMeth="FALSE" getMeth="FALSE" desc='the interPixelFractionXMask field mask' init='0x700000000LL'/> -->
<!--- #    <attribute type='ulonglong' name='interPixelFractionYMask' setMeth="FALSE" getMeth="FALSE" desc='the interPixelFractionYMask field mask' init='0x3800000000LL'/> -->

<!--- Final choice was to hard code the mask. Since they are private it does not hurt outside world. Devellopers needs to be carefull -->
<!--- if changing the bitfield structure: the filed Mask will not automatically be updated. -->

  </class>
</package>
</gdd>

=== ibab/lhcb-software/LHCb/Kernel/LHCbKernel/xml/MuonTileID.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gdd SYSTEM "gdd.dtd">
<gdd>
  <package name='LHCbKernel'>
    <class 
      author  = "Andrei Tsaregorodtsev" 
      desc    = "Universal identifier for the Muon System entities" 
      name    = "MuonTileID"
      virtual = 'FALSE'                                             >
      <import name="Kernel/MuonBase"/>
      <import name="Kernel/MuonLayout"/>
      &StlVector;
      <constructor
        desc="Default constructor"
        initList="m_muonid(0)"/>
      <copyconstructor/>
      <constructor
        desc="Constructor with all the arguments"
        argList="int station,const IMuonLayout lay,
	       int region,int quarter,int x,int y" initList="m_muonid(0)">
        <code>
           setStation(station);
	   setRegion(region);
	   setQuarter(quarter);
	   setX(x);
	   setY(y);
	   setLayout(MuonLayout(lay.grid(*this)));
        </code>	  
      </constructor>
      <constructor
        desc="Constructor from similar MuonTileID"
        argList="const MuonTileID id,
	 const unsigned int region,
	 const unsigned int quarter,
	 const unsigned int x,
	 const unsigned int y" initList="m_muonid(id.m_muonid)">
        <code>
           setQuarter(quarter);
	   setRegion(region);
	   setX(x);
	   setY(y);
        </code>	  
      </constructor>
      <constructor
        desc="Constructor from relative position in the containing MuonTile MuonTileID"
        argList="const MuonTileID id,
                 const IMuonLayout layout,
	         const unsigned int x,
	         const unsigned int y" >	  
      </constructor>
      <constructor
        desc="Constructor taking a long needed for the keyed container"
        argList="const long int muonid" >
	<code>    m_muonid = static_cast&lt;unsigned int&gt;(muonid);</code>
      </constructor>
      <constructor
        desc="Constructor from a string representation of the MuonTileID"
        argList="std::string strid" 
        initList="m_muonid(0)">
	<code>

    const char * str = strid.c_str()+1;
    char * endptr;

    long sta = strtol(str,&amp;endptr,0);
    str = endptr+1;
    long mlx = strtol(str,&amp;endptr,0);
    str = endptr+1;
    long mly = strtol(str,&amp;endptr,0);
    str = endptr+2;
    long quarter = strtol(str,&amp;endptr,0);
    str = endptr+2;
    long region = strtol(str,&amp;endptr,0);
    str = endptr+1;
    long nx = strtol(str,&amp;endptr,0);
    str = endptr+1;
    long ny = strtol(str,&amp;endptr,0);

    setStation(sta);
    setLayout(MuonLayout(mlx,mly));
    setQuarter(quarter);
    setRegion(region);
    setX(nx);
    setY(ny);
	</code>
      </constructor>
      <method const="TRUE"  name="operator long int" type=" "
        desc="convert the MuonTileID to an int for use as a key">
        <code> return static_cast&lt;long int&gt;(m_muonid);</code>
      </method>	 
      <method const="TRUE"  name="station" type="unsigned int"
        inline="TRUE"
        desc="Function to extract station">
        <code> return ( m_muonid &amp; MuonBase::MaskStation ) &gt;&gt; MuonBase::ShiftStation ;</code>
      </method> 
      <method const="TRUE"  name="region" type="unsigned int"
        inline="TRUE"
        desc="Function to extract region">
        <code> return ( m_muonid &amp; MuonBase::MaskRegion ) &gt;&gt; MuonBase::ShiftRegion ;</code>
      </method>
      <method const="TRUE"  name="quarter" type="unsigned int"
        inline="TRUE"
        desc="Function to extract quarter">
        <code> return ( m_muonid &amp; MuonBase::MaskQuarter ) &gt;&gt; MuonBase::ShiftQuarter ;</code>
      </method>
      <method const="TRUE"  name="layout" type="MuonLayout" inline="TRUE"
        desc="Function to extract layout">
        <code> 
          int xg = ( m_muonid &amp; MuonBase::MaskLayoutX ) &gt;&gt; MuonBase::ShiftLayoutX ; 
          int yg = ( m_muonid &amp; MuonBase::MaskLayoutY ) &gt;&gt; MuonBase::ShiftLayoutY ;
          return  MuonLayout(xg,yg) ;
        </code>
      </method>
      <method const="TRUE"  name="nX" type="unsigned int"
        inline="TRUE"
        desc="Function to extract index in x">
        <code> return ( m_muonid &amp; MuonBase::MaskX ) &gt;&gt; MuonBase::ShiftX ;</code>
      </method>
      <method const="TRUE"  name="nY" type="unsigned int"
        inline="TRUE"
        desc="Function to extract index in y">
        <code> return ( m_muonid &amp; MuonBase::MaskY ) &gt;&gt; MuonBase::ShiftY ;</code>
      </method>
      <method const="TRUE"  name="index" type="unsigned int"
        inline="TRUE"
        desc="Function to extract lower part of the identifier">
        <code> return ( m_muonid &amp; MuonBase::MaskIndex ) &gt;&gt; MuonBase::ShiftIndex ;</code>
      </method>
      <method const="TRUE"  name="key" type="unsigned int"
        inline="TRUE"
        desc="Function to extract lower part of the identifier with station information">
        <code> return ( m_muonid &amp; MuonBase::MaskKey ) &gt;&gt; MuonBase::ShiftKey ;</code>
      </method>
     <method const="TRUE"  name="operator&lt;" type="bool"
       inline="TRUE"
       desc="comparison operator using key."
       argList="const MuonTileID id">
        <code> return key() &lt;  id.key() ;</code>
      </method> 
      <method const="TRUE"  name="operator==" type="bool"
        inline="TRUE"
        desc="equality operator using key."
        argList="const MuonTileID id">
        <code> return m_muonid ==  id.m_muonid ;</code>
      </method> 
      <method const="TRUE"  name="operator!=" type="bool"
        inline="TRUE"
        desc="non-equality operator using key."
        argList="const MuonTileID id">
        <code> return !(id == *this) ;</code>
      </method> 
      <method const="TRUE"  name="intercept" type="MuonTileID"
        desc="Find the MuonTileID which is an interception of two MuonTileID&apos;s"
        argList="const MuonTileID id">
      </method>
      <method const="TRUE"  name="containerID" type="MuonTileID"
        desc="Find the MuonTileID of a Tile of a given layout containing this pad"
        argList="const IMuonLayout layout">
      </method>
      <method const="TRUE"  name="neighbourID" type="MuonTileID"
        desc="Find the MuonTileID of a Tile which is a neighbour of this pad"
        argList="int dirX, int dirY">
      </method>
      <method const="TRUE"  name="localX" type="int"
        desc="Get local offset X with respect to the container defined by the given IMuonLayout"
        argList="const IMuonLayout layout">
      </method>
      <method const="TRUE"  name="localY" type="int"
        desc="Get local offset y with respect to the container defined by the given IMuonLayout"
        argList="const IMuonLayout layout">
      </method>
      <method const="TRUE"  name="isValid" type="bool"
        desc="Check that the MuonTileID is consistent in terms of its layout">
      </method>
      <method const="TRUE"  name="isDefined" type="bool"
        desc="Check that the MuonTileID is defined. It means that its code is not 0">
        <code> return m_muonid!=0;</code>  
      </method>
      <method const="TRUE"  name="toString" type="std::string"
        desc="presents the MuonTileID as a readable string">
      </method>
      <method  name="setStation" inline="TRUE"
        desc="update station identifier"
        argList="const unsigned int station">
        <code>set( station, MuonBase::ShiftStation, MuonBase::MaskStation ) ;</code>  
      </method>
      <method  name="setRegion" inline="TRUE"
        desc="update region identifier"
        argList="const unsigned int region">
        <code>  set( region, MuonBase::ShiftRegion, MuonBase::MaskRegion ) ;</code>  
      </method>
      <method  name="setQuarter" inline="TRUE"
        desc="update quarter identifier"
        argList="const unsigned int quarter">
        <code>set( quarter, MuonBase::ShiftQuarter, MuonBase::MaskQuarter ) ;</code>  
      </method>
      <method  name="setX" inline="TRUE"
        desc="update index in x"
        argList="const unsigned int x">
        <code>set( x, MuonBase::ShiftX, MuonBase::MaskX ) ;</code>  
      </method>
      <method  name="setY" inline="TRUE"
        desc="update index in y"
        argList="const unsigned int y">
        <code>set( y, MuonBase::ShiftY, MuonBase::MaskY ) ;</code>  
      </method>
      <method  name="setLayout" inline="TRUE"
        desc="update layout identifier"
        argList="MuonLayout layout">
        <code>
  unsigned int lx, ly;
  lx = layout.xGrid();
  ly = layout.yGrid();
  set( lx, MuonBase::ShiftLayoutX, MuonBase::MaskLayoutX ) ;
  set( ly, MuonBase::ShiftLayoutY, MuonBase::MaskLayoutY ) ;
        </code>  
      </method>
      <method  name="deltaX" inline="TRUE"
        desc="modify index in x"
        argList="int dx">
        <code>  setX(nX() + dx);</code>  
      </method>
      <method  name="deltaY" inline="TRUE"
        desc="modify index in y"
        argList="int dy">
        <code>  setY(nY() + dy);</code>  
      </method>
      <method  name="set" inline="TRUE" access="PRIVATE"
        desc="modify index in y"
        argList="const unsigned int Value, const unsigned int Shift, const unsigned int Mask">
        <code>
  unsigned int tmp1 , tmp2 ;
  tmp1 = ( Value &lt;&lt; Shift ) &amp; Mask ; 
  tmp2 = m_muonid &amp; ~Mask ; 
  m_muonid = ( tmp1 | tmp2 ) ;
        </code>  
      </method>
      <attribute desc="muon tile id" name="muonid" type="unsigned int" 
       setMeth="FALSE" getMeth="FALSE"/>

      <method 
          name    = "fillStream" 
          desc    = "Print this MuonTileID in a human readable way"
          type    = "std::ostream&amp;" 
          virtual = "FALSE" 
          const   = "TRUE">
          <arg 
            type = "std::ostream" 
            name = "s"/>
      </method>

    </class>
  </package>
</gdd>
